In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
1918,1919,CA-2016-123673,30/10/2016,01/11/2016,Second Class,CH-12070,Cathy Hwang,Home Office,United States,Detroit,Michigan,48227.0,Central,TEC-PH-10001809,Technology,Phones,Panasonic KX T7736-B Digital phone,299.90
8451,8452,CA-2015-131387,28/04/2015,30/04/2015,First Class,AI-10855,Arianne Irving,Consumer,United States,San Francisco,California,94122.0,West,TEC-PH-10001459,Technology,Phones,Samsung Galaxy Mega 6.3,1679.96
4380,4381,CA-2016-152891,25/10/2016,30/10/2016,Standard Class,TB-21625,Trudy Brown,Consumer,United States,San Francisco,California,94110.0,West,OFF-AR-10004648,Office Supplies,Art,Boston 19500 Mighty Mite Electric Pencil Sharp...,60.45
2639,2640,CA-2018-108441,12/06/2018,18/06/2018,Standard Class,SB-20170,Sarah Bern,Consumer,United States,New York City,New York,10035.0,East,OFF-AR-10004691,Office Supplies,Art,Boston 1730 StandUp Electric Pencil Sharpener,64.14
6358,6359,CA-2018-139080,23/01/2018,28/01/2018,Standard Class,CS-12250,Chris Selesnick,Corporate,United States,Seattle,Washington,98103.0,West,OFF-PA-10002262,Office Supplies,Paper,Xerox 192,6.48

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [5]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [6]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['sdate'] = pd.to_datetime(df['Ship Date'], dayfirst = True)
df['odate'] = pd.to_datetime(df['Order Date'] , dayfirst = True)

In [9]:
df['omonth'] = df['odate'].dt.month
df['smonth'] = df['sdate'].dt.month

In [10]:
df['oyear'] = df['odate'].dt.year
df['syear'] = df['sdate'].dt.year

In [11]:
df['oquarter'] = df['odate'].dt.quarter
df['squarter'] = df['sdate'].dt.quarter

In [12]:
df.drop(columns = ['Order Date' , 'Ship Date'] , axis = 1 , inplace = True)

In [13]:
df = df.dropna(subset = ["Postal Code"])

In [14]:
# Outliers Detection
q3 = df['Sales'].quantile(0.75)
q1 = df['Sales'].quantile(0.25)
iqr = q3 - q1

In [15]:
high = q3 + 1.5 * iqr
low = q1 - 1.5 * iqr

In [16]:
# Outliers
df[(df['Sales'] > high) | (df['Sales'] < low)]

,Row ID,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,...,Product Name,Sales,sdate,odate,omonth,smonth,oyear,syear,oquarter,squarter
1,2,CA-2017-152156,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017-11-11,2017-11-08,11,11,2017,2017,4,4
3,4,US-2016-108966,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016-10-18,2016-10-11,10,10,2016,2016,4,4
7,8,CA-2015-115812,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,...,Mitel 5320 IP Phone VoIP phone,907.1520,2015-06-14,2015-06-09,6,6,2015,2015,2,2
10,11,CA-2015-115812,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,...,Chromcraft Rectangular Conference Tables,1706.1840,2015-06-14,2015-06-09,6,6,2015,2015,2,2
11,12,CA-2015-115812,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,...,Konftel 250 Conference phone - Charcoal black,911.4240,2015-06-14,2015-06-09,6,6,2015,2015,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9759,9760,CA-2017-146913,Standard Class,SF-20965,Sylvia Foulston,Corporate,United States,San Francisco,California,94109.0,...,Office Star - Professional Matrix Back Chair w...,1403.9200,2017-11-05,2017-10-31,10,11,2017,2017,4,4
9774,9775,CA-2015-169019,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,Texas,78207.0,...,GBC DocuBind P400 Electric Binding System,2177.5840,2015-07-30,2015-07-26,7,7,2015,2015,3,3
9781,9782,CA-2017-153178,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Long Beach,New York,11561.0,...,GBC DocuBind 200 Manual Binding Machine,673.5680,2017-09-18,2017-09-14,9,9,2017,2017,3,3
9787,9788,CA-2018-144491,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,...,"Atlantic Metals Mobile 5-Shelf Bookcases, Cust...",1023.3320,2018-04-01,2018-03-27,3,4,2018,2018,1,2
9788,9789,CA-2018-144491,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,...,Global Deluxe High-Back Manager's Chair,600.5580,2018-04-01,2018-03-27,3,4,2018,2018,1,2

In [17]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'sdate', 'odate', 'omonth', 'smonth', 'oyear', 'syear', 'oquarter', 'squarter']

In [18]:
df["Shipping Days"] = (pd.to_datetime(df["sdate"]) - pd.to_datetime(df["odate"])).dt.days

In [19]:
df.drop(columns = ['sdate' , 'odate'] , axis = 1 , inplace = True)

In [20]:
import mysql.connector
import pandas as pd
from sqlalchemy import create_engine

conn = mysql.connector.connect(
    host = "localhost",user = "root" , password = "Manan274545", database = "sales_db")
cursor = conn.cursor()

In [21]:
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:Manan274545@localhost/sales_db")

df.to_sql("sales", con=engine, if_exists="replace", index=False)

9789

In [22]:
df.to_csv('cleaned_sales.csv' , index = False)

In [23]:
df.to_csv('cleaned_sales_v2.csv', index=False)

In [1]:
import os

print(os.getcwd())

C:\Users\Lenovo

In [ ]:
import shutil

shutil.copy(
    "cleaned_sales.csv",
    r"C:\Users\Lenovo"
)